// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esumcczfkkkyycpougkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdW1jY3pma2treXljcG91Z2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Mjg2NTgsImV4cCI6MjA1ODEwNDY1OH0.9gbbtGRXp0JWkTxhuRZz9s6uVwotbPWKm0hUcI4uCT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);